[tool.poetry]
name = "pixiv-dl"
version = "0.1.0"
description = ""
authors = ["Laura F Dickinson <l@veriny.tf>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pixivpy = "^3.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
